MastodonC/witan.gateway

project.clj
src/witan/gateway/components/query_router.clj
src/witan/gateway/handler.clj
src/witan/gateway/queries/data_acquisition.clj
src/witan/gateway/queries/workspace.clj
test/witan/gateway/components/query_router_test.clj

The gateway will, in time, reach out to other services in order to resolve queries

Queries are now resolved in the gateway

---

circle.yml
project.clj
resources/config.edn
src/witan/gateway/components/connection_manager.clj
src/witan/gateway/components/query_router.clj
src/witan/gateway/queries/data_acquisition.clj
src/witan/gateway/system.clj
test/witan/gateway/integration/system_test.clj

This is a combinations of changes which facilitates getting events back to the frontend

Events are now sent back to the originating client

---

circle.yml
docker-compose.yml
resources/config.edn
src/witan/gateway/components/connection_manager.clj
src/witan/gateway/components/query_router.clj
src/witan/gateway/components/server.clj
src/witan/gateway/handler.clj
src/witan/gateway/queries/data_acquisition.clj
src/witan/gateway/system.clj
test/witan/gateway/integration/base.clj
test/witan/gateway/integration/system_test.clj

Adds routes to the gateway to facilitate signing into Heimdall via HTTP.

Integration with heimdall: sign-in

---

src/witan/gateway/system.clj

Re-add queries to component deps

---

src/witan/gateway/handler.clj

We use the existing websocket connection to issue a 'refresh' command which contacts heimdall and returns new keys.

Add refreshing tokens via a 'refresh' message

---

project.clj

Use new kixi.comms

---

project.clj
resources/config.edn
src/witan/gateway/components/server.clj
src/witan/gateway/handler.clj

- Store the stream of the multipart pieces (if file)
- Recreate the request by forwarding the headers

Upload to the datastore spike

---

src/witan/gateway/handler.clj

Prevents an exception when datastore returns a non-json 404 response

Better 404 handling

---

src/witan/gateway/handler.clj

This is so we can use the ID in the frontend

Send back the ID of the resource

---

resources/config.edn

Allow topic override with env var

---

run-against-staging.sh

This script adds an entry to the /etc/hosts file and sets up ssh
tunnels to communicate to the staging services.

Adding staging run script

---

resources/config.edn

**Fix kinesis metric disabling**

Fix kinesis metric disabling

---

deployment/production-marathon.json

Fix upgrade strategy

---

deployment/production-marathon.json

**Fix minimum health capacity to allow deploys**

Fix minimum health capacity to allow deploys

---

project.clj

**Our PR got merged so we don't need our own branch anymore**

Upgrade clj-http

---

src/witan/gateway/components/query_router.clj
src/witan/gateway/handler.clj
src/witan/gateway/queries/datastore.clj
test/witan/gateway/integration/base.clj
test/witan/gateway/integration/query_test.clj
test/witan/gateway/integration/system_test.clj

We also did a little clean up of tests

Add support for paging datastore files queries

---

src/witan/gateway/handler.clj
src/witan/gateway/queries/datastore.clj
test/witan/gateway/integration/query_test.clj

It was inside the activities vector which is just plain wrong

The opts param was in the wrong place.

---

src/witan/gateway/handler.clj

**Add a partition key selector for `:kixi.collect/collection-requested`**

Add a partition key selector for `:kixi.collect/collection-requested`

---

.gitignore
deployment/production-marathon.json
deployment/witan-gateway.json.template

**Normalize the app name**
- will fix alerting on witan.gateway

Normalize the app name

---

src/witan/gateway/components/server.clj
test/witan/gateway/integration/query_test.clj

**Add the request to the log when the middleware catches an exception**

Add the request to the log when the middleware catches an exception

---

src/witan/gateway/components/query_router.clj
src/witan/gateway/queries/search.clj

**Add metadata-by-id route**
**Fix bad url**

Add metadata-by-id route

---

src/witan/gateway/handler.clj

**Add partition key for new `sharing-change` command**
This is necessary for the UI to use the new command

Add partition key for new `sharing-change` command

---

src/witan/gateway/components/query_router.clj
test/witan/gateway/integration/query_test.clj

**Add query endpoint for getting groups by id**
The query already existed, just didn't have endpoint or test

Add query endpoint for getting groups by id
